issuer: Government of Maharashtra - Application for Intimation
keywords:
  - महाराष्ट्र दुकाने व आस्थापना
  - APPLICATION FOR INTIMATION
fields:
  name_of_establishment: Name of the establishment(?:[\S\s]*?)([A-Z .&-/]{6,})
  name_of_employer: Name of the Employer(?:[\S\s]*?)([A-Z .]{6,})